-- LV.4
SELECT P.PRODUCT_ID, PRODUCT_NAME, SUM(AMOUNT*PRICE) as TOTAL_SALES
FROM FOOD_PRODUCT P, FOOD_ORDER O
WHERE P.PRODUCT_ID=O.PRODUCT_ID
      AND TO_CHAR(PRODUCE_DATE,'yyyy-mm') = '2022-05'
GROUP BY P.PRODUCT_ID, PRODUCT_NAME
ORDER BY TOTAL_SALES desc, PRODUCT_ID;