-- LV.4
SELECT CAR.CAR_ID, CAR.CAR_TYPE, (DAILY_FEE*((100-RATE)/100))*30 AS FEE
FROM (SELECT CAR_ID, CAR_TYPE, DAILY_FEE
      FROM CAR_RENTAL_COMPANY_CAR
      WHERE CAR_TYPE IN ('세단', 'SUV')
            AND CAR_ID NOT IN (SELECT CAR_ID
                               FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                               WHERE START_DATE<=TO_DATE('2022-11-30', 'YYYY-MM-DD')
                               AND END_DATE>=TO_DATE('2022-11-01', 'YYYY-MM-DD'))) "CAR",
     (SELECT CAR_TYPE, TO_NUMBER(REPLACE(DISCOUNT_RATE, '%', '')) AS RATE
       FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
       WHERE DURATION_TYPE LIKE '30일 이상'
      ) "DISCOUNT"
WHERE CAR.CAR_TYPE = DISCOUNT.CAR_TYPE
      AND (DAILY_FEE*((100-RATE)/100))*30 BETWEEN 500000 AND 2000000
ORDER BY FEE desc, CAR.CAR_TYPE, CAR.CAR_ID desc;