-- LV.3
SELECT TO_NUMBER(TO_CHAR(START_DATE,'FMmm')) as MONTH, CAR_ID, count(*) as RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (SELECT CAR_ID
                 FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                 WHERE TO_CHAR(START_DATE,'yyyy-mm') BETWEEN '2022-08' AND '2022-10'
                 GROUP BY CAR_ID
                 HAVING count(*) >= 5)
      AND TO_CHAR(START_DATE,'yyyy-mm') BETWEEN '2022-08' AND '2022-10'
GROUP BY CAR_ID, TO_NUMBER(TO_CHAR(START_DATE,'FMmm'))
HAVING count(*) > 0
ORDER BY MONTH, CAR_ID desc;