-- LV.3
SELECT DISTINCT c.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR c, CAR_RENTAL_COMPANY_RENTAL_HISTORY h
WHERE c.CAR_ID = h.CAR_ID
      AND CAR_TYPE = '세단'
      AND TO_CHAR(START_DATE,'mm') = '10'
ORDER BY CAR_ID desc;