-- LV.3
SELECT ANIMAL_ID, NAME
FROM (SELECT I.ANIMAL_ID, I.NAME, O.DATETIME-I.DATETIME as period
      FROM ANIMAL_INS I, ANIMAL_OUTS O
      WHERE I.ANIMAL_ID = O.ANIMAL_ID
      ORDER BY period DESC)
WHERE ROWNUM<=2;