-- LV.4
SELECT D.HOUR, NVL(O.COUNT,0) as COUNT
FROM (SELECT TO_CHAR(DATETIME,'fmhh24') as HOUR, COUNT(*) as COUNT
      FROM ANIMAL_OUTS
      GROUP BY TO_CHAR(DATETIME,'fmhh24')) O,
      (SELECT LEVEL-1 as HOUR
      FROM DUAL
      CONNECT BY LEVEL <= 24) D
WHERE O.HOUR (+)= D.HOUR
ORDER BY HOUR;