-- LV.4
SELECT I.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, SCORE
FROM REST_INFO I,
     (SELECT REST_ID, ROUND(AVG(REVIEW_SCORE),2) as SCORE
     FROM REST_REVIEW
     GROUP BY REST_ID) R
WHERE ADDRESS LIKE '서울%'
      AND I.REST_ID=R.REST_ID
ORDER BY SCORE desc, FAVORITES desc;