-- LV.3
SELECT ID, CASE WHEN NTILE(4) OVER(ORDER BY SIZE_OF_COLONY desc) = 1 THEN "CRITICAL"
                WHEN NTILE(4) OVER(ORDER BY SIZE_OF_COLONY desc) = 2 THEN "HIGH"
                WHEN NTILE(4) OVER(ORDER BY SIZE_OF_COLONY desc) = 3 THEN "MEDIUM"
                WHEN NTILE(4) OVER(ORDER BY SIZE_OF_COLONY desc) = 4 THEN "LOW" END COLONY_NAME
FROM ECOLI_DATA
ORDER BY ID;