-- LV.4
SELECT F.CATEGORY, MAX_PRICE, F.PRODUCT_NAME
FROM FOOD_PRODUCT F,
     (SELECT CATEGORY, MAX(PRICE) as MAX_PRICE
      FROM FOOD_PRODUCT
      WHERE CATEGORY IN ('과자','국','김치','식용유')
      GROUP BY CATEGORY) M
WHERE F.CATEGORY = M.CATEGORY
      AND F.PRICE = M.MAX_PRICE
ORDER BY MAX_PRICE desc;