-- LV.3
SELECT ID, (SELECT FISH_NAME
            FROM FISH_NAME_INFO
            WHERE F.FISH_TYPE = FISH_TYPE) FISH_NAME, F.LENGTH
FROM FISH_INFO F, (SELECT FISH_TYPE, MAX(LENGTH) LENGTH
                 FROM FISH_INFO
                 GROUP BY FISH_TYPE) M
WHERE F.FISH_TYPE = M.FISH_TYPE
      AND F.LENGTH = M.LENGTH
ORDER BY ID;

